export type RunCoreErrorCode =
  | 'RUN_INTENT_INVALID'
  | 'RUN_IDEMPOTENCY_INVALID'
  | 'RUN_ACCEPTANCE_RECEIPT_INVALID'
  | 'RUN_ACCEPTANCE_INVALID'
  | 'RUN_ADMISSION_SNAPSHOT_INVALID'
  | 'RUN_CONVERSATION_CAS_INVALID'
  | 'RUN_CONVERSATION_CAS_STALE'
  | 'RUN_CONVERSATION_CAS_OVERFLOW'
  | 'RUN_CONVERSATION_IDENTITY_MISMATCH'
  | 'RUN_STATE_INVALID'
  | 'RUN_STATE_TRANSITION_INVALID'
  | 'RUN_TERMINAL_IMMUTABLE'
  | 'RUN_OUTPUT_VALIDATOR_UNAVAILABLE'
  | 'RUN_OUTPUT_INVALID'
  | 'RUN_HUMAN_GATE_APPLY_UNAVAILABLE'
  | 'RUN_HUMAN_GATE_INVALID'
  | 'RUN_HUMAN_GATE_EXPIRED'
  | 'RUN_HUMAN_GATE_CONFLICT'
  | 'RUN_JOIN_CHILD_INVALID'
  | 'RUN_JOIN_CHILD_DENIED'
  | 'RUN_RETENTION_INVALID'
  | 'RUN_LEASE_INVALID'
  | 'RUN_LEASE_AUTHORITY_MISMATCH'
  | 'RUN_LEASE_EXPIRED'
  | 'RUN_LEASE_TRANSITION_INVALID'
  | 'RUN_LEASE_FENCING_OVERFLOW'
  | 'RUN_RECOVERY_INVALID'
  | 'RUN_RECOVERY_IDENTITY_MISMATCH'
  | 'RUN_RECOVERY_DISPOSITION_CONFLICT'
  | 'RUN_EFFECT_CLOSURE_UNSAFE'
  | 'RUN_LEASED_MUTATION_INVALID'
  | 'RUN_DISPATCH_INVALID'
  | 'RUN_DISPATCH_RETIREMENT_CONFLICT'
  | 'RUN_FLOW_LLM_INVALID'
  | 'RUN_STRATEGY_CHECKPOINT_INVALID'
  | 'RUN_STRATEGY_DECISION_INVALID'
  | 'RUN_STRATEGY_OBSERVATION_INVALID';

export class RunCoreError extends Error {
  constructor(
    readonly code: RunCoreErrorCode,
    readonly path: string,
    readonly reason: string,
    options: { cause?: unknown } = {},
  ) {
    super(`${code}: ${reason} at ${path}`, options);
    this.name = 'RunCoreError';
  }
}

export function failRunCore(
  code: RunCoreErrorCode,
  path: string,
  reason: string,
  options?: { cause?: unknown },
): never {
  throw new RunCoreError(code, path, reason, options);
}
