export type ReleaseCoreErrorCode =
  | 'CAPABILITY_OPERATION_CONTRACT_MISMATCH'
  | 'SKILL_PACK_OPERATION_UNRESOLVED'
  | 'FEATURE_NOT_ENABLED'
  | 'CLOSURE_SOURCE_INVALID'
  | 'CLOSURE_SOURCE_LIMIT_EXCEEDED'
  | 'CLOSURE_SOURCE_MISMATCH'
  | 'CAPABILITY_GRAPH_INPUT_INVALID'
  | 'CAPABILITY_GRAPH_HASH_MISMATCH'
  | 'CAPABILITY_DEPENDENCY_UNRESOLVED'
  | 'CAPABILITY_DEPENDENCY_CYCLE'
  | 'CAPABILITY_CLOSURE_LIMIT_EXCEEDED'
  | 'CLOSURE_POLICY_INPUT_INVALID'
  | 'CLOSURE_POLICY_LIMIT_EXCEEDED'
  | 'CLOSURE_POLICY_REQUIREMENT_UNAVAILABLE'
  | 'CLOSURE_IDENTITY_INPUT_INVALID'
  | 'CLOSURE_IDENTITY_LIMIT_EXCEEDED'
  | 'CLOSURE_IDENTITY_MISMATCH'
  | 'CLOSURE_BINDING_PATH_DUPLICATE'
  | 'BINDING_PATH_DIGEST_COLLISION'
  | 'RESOURCE_NODE_ID_COLLISION'
  | 'RELEASE_CANONICALIZATION_INVALID'
  | 'RELEASE_HASH_PROFILE_INVALID'
  | 'RELEASE_INPUT_INVALID'
  | 'RELEASE_DRAFT_FORBIDDEN'
  | 'RELEASE_KIND_UNSUPPORTED'
  | 'RELEASE_KIND_MISMATCH'
  | 'RELEASE_HASH_MISMATCH'
  | 'RELEASE_WORKSPACE_MISMATCH'
  | 'RELEASE_DEPENDENCY_INVALID'
  | 'RELEASE_DEPENDENCY_UNREGISTERED'
  | 'RELEASE_EXPERIENCE_INCOMPATIBLE'
  | 'RELEASE_CREDENTIAL_MAPPING_INVALID'
  | 'RELEASE_DEPLOYMENT_INVALID'
  | 'RELEASE_ADMISSION_SNAPSHOT_INVALID';

export class ReleaseCoreError extends Error {
  constructor(
    readonly code: ReleaseCoreErrorCode,
    readonly path: string,
    readonly reason: string,
  ) {
    super(`${code}: ${reason} at ${path}`);
    this.name = 'ReleaseCoreError';
  }
}
